### ISSUE TITLE
HIGH PRIORITY: Fig. 4: 3D Model of suites of traits across latitudinal range (1/4)

### ISSUE THREAD

**Issue by alicelinder** [alicelinder/senior-moment#13]

**Comment by alicelinder** [comment]
Having trouble with code on finding means of traits at each site for each species. How do I use aggregate while having NAs? I put na.rm=TRUE at the end of the function, but I still get warnings and it inserts "NaN" into the dataframe.

**Comment by lizzieinvancouver** [comment]
Check out documentation in aggregate: 

?aggregate

The command is different than summations or means. Try na.action=na.omit.
