### ISSUE TITLE
Make changes to methods (12/23)

### ISSUE THREAD

**Issue by alicelinder** [alicelinder/senior-moment#19]

**Comment by alicelinder** [comment]
@lizzieinvancouver , you mentioned learning to use LaTex to write. Do you recommend any text editors? Do I need to do anything special with layout?

Thanks!

**Comment by lizzieinvancouver** [comment]
Happy New Year Alice! You don't have to use LaTeX at all, but if you want to try it out from afar check out here: http://temporalecology.org/resources/#late and especially go through the Eli Holmes' workshop I mention. If you decide you want to do it I can help over email or Skype with any issues.
