### ISSUE TITLE
write methods (12/2)

### ISSUE THREAD

**Issue by alicelinder** [alicelinder/senior-moment#3]

**Comment by alicelinder** [comment]
[Cornwell_et_al-2006-Ecology.pdf](https://github.com/alicelinder/senior-moment/files/623009/Cornwell_et_al-2006-Ecology.pdf)
[Ettinger-AMJBotany-2013.pdf](https://github.com/alicelinder/senior-moment/files/623016/Ettinger-AMJBotany-2013.pdf)
[Mat-as_et_al-2015-Global_Change_Biology.pdf](https://github.com/alicelinder/senior-moment/files/623020/Mat-as_et_al-2015-Global_Change_Biology.pdf)
[Purves-2009-PRSB.pdf](https://github.com/alicelinder/senior-moment/files/623027/Purves-2009-PRSB.pdf)
[Stahl_2014_PNAS.pdf](https://github.com/alicelinder/senior-moment/files/623030/Stahl_2014_PNAS.pdf)
[Zhu_et_al-2012-Global_Change_Biology.pdf](https://github.com/alicelinder/senior-moment/files/623036/Zhu_et_al-2012-Global_Change_Biology.pdf)
[Zimmerman_et_al-2009-PNAS.pdf](https://github.com/alicelinder/senior-moment/files/623039/Zimmerman_et_al-2009-PNAS.pdf)

**Comment by alicelinder** [comment]
Is there a record of the lab's justification for choosing the 4 sites?

**Comment by alicelinder** [comment]
Do I use "we" or "I"?

**Comment by alicelinder** [comment]
How do I find methods for Harry's data collection? Should I talk to him, or use his proposal from his summer project?

**Comment by lizzieinvancouver** [comment]
Use 'I' for your thesis ('we' if you ever work it up into a manuscript!). That said for stuff others did in your thesis (like Harry) you might say who did it first they refer to them/they.

Sites were chosen to represent a gradient of similar forest composition ranging from HF in the south to the boreal-temperate transition zone in the north. They were picked for composition, to be as equidistant North-South as possible (aiming to keep them about 1 deg apart) and finally -- after all that -- just what was logistically feasible!

**Comment by lizzieinvancouver** [comment]
I would check out Harry's thesis last summer! And pester Dan for an answer to that question.

**Comment by lizzieinvancouver** [comment]
To get on WeldShare just reach out to Stephen Hill (either email or swing by his office he suggested, when I chatted with him yesterday (1 Dec).
